import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/Providers/Providers";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4 bg-gradient-to-br from-black via-zinc-900 to-black`}
      >
        <Providers>
          <AppSidebar />
          {/* <Header></Header> */}
          <main className="w-full">
            <SidebarTrigger></SidebarTrigger>
            {children}
          </main>
        </Providers>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
